from registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.7
run apt update; apt install -y ca-certificates curl wget vim net-tools
run apt reinstall -y bash bash-completion

entrypoint ["/bin/bash"]